import { StyleSheet } from '@react-pdf/renderer';
import type { ValuationLocale } from '../../api_client';
import { PDF_COLORS } from './theme';
import { pdfFontFamily } from './fonts/families';

/** A4 print margins: 20mm vertical, 15mm horizontal */
const MM = 72 / 25.4;
const MARGIN_H = 15 * MM;
const MARGIN_V = 20 * MM;

export function createReportStyles(locale: ValuationLocale) {
  const rtl = locale === 'he';
  const font = pdfFontFamily(locale);
  const row = rtl ? 'row-reverse' : 'row';

  return StyleSheet.create({
    page: {
      fontFamily: font,
      fontSize: 10,
      color: PDF_COLORS.slate,
      backgroundColor: PDF_COLORS.pageBg,
      paddingTop: 0,
      paddingBottom: MARGIN_V + 28,
      direction: rtl ? 'rtl' : 'ltr',
    },
    pageBody: {
      paddingHorizontal: MARGIN_H,
      paddingTop: 12,
    },
    topBar: {
      backgroundColor: PDF_COLORS.darkGreen,
      paddingVertical: 22,
      paddingHorizontal: MARGIN_H,
    },
    topBarRow: {
      flexDirection: row,
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    logo: {
      fontSize: 20,
      fontWeight: 700,
      color: PDF_COLORS.mint,
      letterSpacing: 2.5,
    },
    logoTag: {
      fontSize: 7.5,
      color: PDF_COLORS.white,
      marginTop: 3,
      textAlign: rtl ? 'right' : 'left',
    },
    metaBlock: {
      alignItems: rtl ? 'flex-start' : 'flex-end',
    },
    metaLabel: {
      fontSize: 7,
      color: 'rgba(255,255,255,0.65)',
      textAlign: rtl ? 'left' : 'right',
    },
    metaValue: {
      fontSize: 8.5,
      fontWeight: 700,
      color: PDF_COLORS.white,
      textAlign: rtl ? 'left' : 'right',
    },
    coverTitle: {
      fontSize: 11,
      color: PDF_COLORS.mint,
      fontWeight: 700,
      marginTop: 14,
      textAlign: rtl ? 'right' : 'left',
      letterSpacing: 0.5,
    },
    companyHero: {
      fontSize: 22,
      fontWeight: 700,
      color: PDF_COLORS.white,
      marginTop: 4,
      textAlign: rtl ? 'right' : 'left',
    },
    divider: {
      height: 2,
      backgroundColor: PDF_COLORS.mint,
      marginVertical: 14,
      width: '100%',
    },
    heroBox: {
      backgroundColor: PDF_COLORS.darkGreen,
      borderRadius: 8,
      padding: 22,
      marginBottom: 16,
      borderWidth: 2,
      borderColor: PDF_COLORS.mint,
    },
    heroLabel: {
      fontSize: 9,
      color: PDF_COLORS.mint,
      fontWeight: 700,
      textAlign: 'center',
      marginBottom: 6,
      letterSpacing: 1,
    },
    heroValue: {
      fontSize: 32,
      fontWeight: 700,
      color: PDF_COLORS.white,
      textAlign: 'center',
    },
    heroSub: {
      fontSize: 10,
      color: 'rgba(255,255,255,0.85)',
      textAlign: rtl ? 'right' : 'left',
      marginTop: 4,
    },
    heroMainLine: {
      fontSize: 14,
      fontWeight: 700,
      color: PDF_COLORS.white,
      textAlign: rtl ? 'right' : 'left',
      marginBottom: 4,
    },
    bulletCompact: {
      fontSize: 10,
      lineHeight: 1.45,
      color: PDF_COLORS.slate,
      textAlign: rtl ? 'right' : 'left',
      marginBottom: 6,
    },
    healthTile: {
      flex: 1,
      backgroundColor: PDF_COLORS.white,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 6,
      padding: 8,
      marginHorizontal: 3,
      marginBottom: 6,
    },
    healthStatus: {
      fontSize: 9,
      fontWeight: 700,
      marginTop: 4,
    },
    rangeCard: {
      backgroundColor: PDF_COLORS.white,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      padding: 14,
      marginBottom: 14,
    },
    rangeTitleRow: {
      flexDirection: row,
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: 700,
      color: PDF_COLORS.darkGreen,
      textAlign: rtl ? 'right' : 'left',
    },
    confidenceBadge: {
      backgroundColor: PDF_COLORS.mintSoft,
      borderWidth: 1,
      borderColor: PDF_COLORS.mint,
      borderRadius: 12,
      paddingVertical: 3,
      paddingHorizontal: 10,
    },
    confidenceText: {
      fontSize: 8,
      fontWeight: 700,
      color: PDF_COLORS.darkGreen,
    },
    gaugeTrack: {
      height: 10,
      backgroundColor: PDF_COLORS.mintSoft,
      borderRadius: 5,
      marginBottom: 8,
      position: 'relative',
    },
    gaugeFill: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      backgroundColor: PDF_COLORS.mint,
      borderRadius: 5,
      opacity: 0.35,
    },
    gaugeMarker: {
      position: 'absolute',
      top: -3,
      width: 4,
      height: 16,
      backgroundColor: PDF_COLORS.darkGreen,
      borderRadius: 2,
    },
    gaugeMarkerBase: {
      backgroundColor: PDF_COLORS.mint,
      width: 5,
      height: 18,
      top: -4,
    },
    rangeLabels: {
      flexDirection: row,
      justifyContent: 'space-between',
    },
    rangeCol: {
      flex: 1,
      alignItems: 'center',
    },
    rangeCaseLabel: {
      fontSize: 7,
      color: PDF_COLORS.slateMuted,
      fontWeight: 700,
      marginBottom: 2,
    },
    rangeCaseValue: {
      fontSize: 9,
      fontWeight: 700,
      color: PDF_COLORS.darkGreen,
    },
    metricsGrid: {
      flexDirection: row,
      flexWrap: 'wrap',
      marginBottom: 12,
    },
    metricsRow3: {
      flexDirection: row,
      marginBottom: 14,
    },
    metricTileThird: {
      flex: 1,
      backgroundColor: PDF_COLORS.white,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 6,
      padding: 10,
      marginHorizontal: 4,
    },
    metricTile: {
      width: '48%',
      backgroundColor: PDF_COLORS.white,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 6,
      padding: 10,
      marginBottom: 8,
      marginHorizontal: '1%',
    },
    metricTileLabel: {
      fontSize: 7.5,
      color: PDF_COLORS.slateMuted,
      marginBottom: 4,
      textAlign: rtl ? 'right' : 'left',
    },
    metricTileValue: {
      fontSize: 12,
      fontWeight: 700,
      color: PDF_COLORS.darkGreen,
      textAlign: rtl ? 'right' : 'left',
    },
    summaryStrip: {
      backgroundColor: PDF_COLORS.mintSoft,
      borderRightWidth: rtl ? 0 : 3,
      borderLeftWidth: rtl ? 3 : 0,
      borderColor: PDF_COLORS.mint,
      padding: 12,
      borderRadius: 4,
      marginTop: 4,
    },
    summaryText: {
      fontSize: 8.5,
      lineHeight: 1.5,
      color: PDF_COLORS.slate,
      textAlign: rtl ? 'right' : 'left',
    },
    pageHeader: {
      flexDirection: row,
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      paddingBottom: 8,
      borderBottomWidth: 2,
      borderBottomColor: PDF_COLORS.mint,
    },
    pageHeaderTitle: {
      fontSize: 13,
      fontWeight: 700,
      color: PDF_COLORS.darkGreen,
      textAlign: rtl ? 'right' : 'left',
    },
    pageHeaderRef: {
      fontSize: 7.5,
      color: PDF_COLORS.slateMuted,
    },
    table: {
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 6,
      overflow: 'hidden',
      marginBottom: 16,
      backgroundColor: PDF_COLORS.white,
    },
    tableHead: {
      flexDirection: row,
      backgroundColor: PDF_COLORS.darkGreen,
      paddingVertical: 7,
      paddingHorizontal: 10,
    },
    th: {
      flex: 1,
      fontSize: 8,
      fontWeight: 700,
      color: PDF_COLORS.white,
      textAlign: rtl ? 'right' : 'left',
    },
    thRight: {
      textAlign: rtl ? 'left' : 'right',
    },
    tr: {
      flexDirection: row,
      paddingVertical: 7,
      paddingHorizontal: 10,
      borderBottomWidth: 1,
      borderBottomColor: PDF_COLORS.border,
    },
    trAlt: {
      backgroundColor: PDF_COLORS.mintSoft,
    },
    trTotal: {
      backgroundColor: PDF_COLORS.darkGreen,
    },
    td: {
      flex: 1,
      fontSize: 10,
      textAlign: rtl ? 'right' : 'left',
    },
    tdRight: {
      textAlign: rtl ? 'left' : 'right',
      fontWeight: 700,
      color: PDF_COLORS.darkGreen,
    },
    tdWhite: {
      color: PDF_COLORS.white,
      fontWeight: 700,
    },
    waccGrid: {
      flexDirection: row,
      flexWrap: 'wrap',
      marginBottom: 8,
    },
    waccTile: {
      width: '31%',
      marginHorizontal: '1%',
      marginBottom: 8,
      backgroundColor: PDF_COLORS.white,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 6,
      padding: 10,
    },
    waccTileAccent: {
      borderColor: PDF_COLORS.mint,
      borderWidth: 2,
      backgroundColor: PDF_COLORS.mintSoft,
    },
    bulletRow: {
      flexDirection: row,
      marginBottom: 10,
    },
    bulletDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: PDF_COLORS.mint,
      marginTop: 4,
      marginLeft: rtl ? 8 : 0,
      marginRight: rtl ? 0 : 8,
    },
    bulletText: {
      flex: 1,
      fontSize: 9,
      lineHeight: 1.55,
      color: PDF_COLORS.slate,
      textAlign: rtl ? 'right' : 'left',
    },
    disclaimerBox: {
      marginTop: 16,
      padding: 12,
      backgroundColor: PDF_COLORS.white,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 6,
    },
    disclaimerTitle: {
      fontSize: 8,
      fontWeight: 700,
      color: PDF_COLORS.slateMuted,
      marginBottom: 4,
      textAlign: rtl ? 'right' : 'left',
    },
    disclaimerText: {
      fontSize: 7,
      lineHeight: 1.45,
      color: PDF_COLORS.slateMuted,
      textAlign: rtl ? 'right' : 'left',
    },
    footer: {
      position: 'absolute',
      bottom: MARGIN_V,
      left: MARGIN_H,
      right: MARGIN_H,
      borderTopWidth: 1,
      borderTopColor: PDF_COLORS.border,
      paddingTop: 6,
      flexDirection: row,
      justifyContent: 'space-between',
    },
    footerText: {
      fontSize: 7,
      color: PDF_COLORS.slateMuted,
    },
    footerPage: {
      fontSize: 7,
      color: PDF_COLORS.mint,
      fontWeight: 700,
    },
    iconRow: {
      flexDirection: row,
      alignItems: 'center',
      marginBottom: 8,
    },
    iconLabel: {
      fontSize: 8,
      color: PDF_COLORS.slateMuted,
      marginLeft: rtl ? 0 : 6,
      marginRight: rtl ? 6 : 0,
    },
    coverPage: {
      backgroundColor: PDF_COLORS.darkGreen,
      padding: 48,
      justifyContent: 'space-between',
      minHeight: '100%',
    },
    coverLogo: {
      fontSize: 36,
      fontWeight: 700,
      color: PDF_COLORS.mint,
      letterSpacing: 4,
      textAlign: 'center',
    },
    coverPageTitle: {
      fontSize: 24,
      fontWeight: 700,
      color: PDF_COLORS.white,
      textAlign: 'center',
      marginTop: 48,
    },
    coverCompany: {
      fontSize: 18,
      color: PDF_COLORS.mint,
      textAlign: 'center',
      marginTop: 12,
    },
    coverMeta: {
      marginTop: 40,
      borderTopWidth: 2,
      borderTopColor: PDF_COLORS.mint,
      paddingTop: 20,
    },
    coverMetaRow: {
      flexDirection: row,
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    coverMetaLabel: {
      fontSize: 9,
      color: 'rgba(255,255,255,0.65)',
    },
    coverMetaValue: {
      fontSize: 10,
      fontWeight: 700,
      color: PDF_COLORS.white,
    },
    dualHeroRow: {
      flexDirection: row,
      marginBottom: 14,
    },
    dualHeroBox: {
      flex: 1,
      backgroundColor: PDF_COLORS.darkGreen,
      borderRadius: 8,
      padding: 16,
      marginHorizontal: 4,
      borderWidth: 1,
      borderColor: PDF_COLORS.mint,
    },
    contextBox: {
      backgroundColor: PDF_COLORS.white,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 8,
      padding: 16,
      marginBottom: 14,
      borderRightWidth: rtl ? 1 : 4,
      borderLeftWidth: rtl ? 4 : 1,
      borderRightColor: rtl ? PDF_COLORS.border : PDF_COLORS.mint,
      borderLeftColor: rtl ? PDF_COLORS.mint : PDF_COLORS.border,
    },
    contextText: {
      fontSize: 9.5,
      lineHeight: 1.6,
      color: PDF_COLORS.slate,
      textAlign: rtl ? 'right' : 'left',
    },
    barTrack: {
      height: 14,
      backgroundColor: PDF_COLORS.mintSoft,
      borderRadius: 7,
      marginVertical: 8,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
    },
    barFill: {
      height: 14,
      backgroundColor: PDF_COLORS.mint,
      borderRadius: 7,
    },
    barLegend: {
      flexDirection: row,
      justifyContent: 'space-between',
      marginTop: 4,
    },
    barLegendText: {
      fontSize: 8,
      color: PDF_COLORS.slateMuted,
    },
    sensitivityCell: {
      flex: 1,
      padding: 8,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
    },
    sensitivityCellBase: {
      backgroundColor: PDF_COLORS.mintSoft,
      borderColor: PDF_COLORS.mint,
      borderWidth: 2,
    },
    sensitivityHeader: {
      flex: 1,
      padding: 6,
      backgroundColor: PDF_COLORS.darkGreen,
      alignItems: 'center',
    },
    sensitivityHeaderText: {
      fontSize: 7.5,
      fontWeight: 700,
      color: PDF_COLORS.white,
    },
    scenarioCol: {
      flex: 1,
      borderWidth: 1,
      borderColor: PDF_COLORS.border,
      borderRadius: 6,
      padding: 10,
      marginHorizontal: 3,
      backgroundColor: PDF_COLORS.white,
      alignItems: 'center',
    },
    scenarioColBase: {
      borderColor: PDF_COLORS.mint,
      borderWidth: 2,
      backgroundColor: PDF_COLORS.mintSoft,
    },
  });
}
