import type { ForecastMatrixWithDiagnostics } from '../../valuation_forecast';
import type { ValuationLocale } from '../../api_client';
import { ebitdaMargin, formatMoney, scenarioValues } from './formatters';

export interface StrategicRecommendations {
  title: string;
  bullets: string[];
  disclaimer: string;
}

function avgGrowth(rates: number[]): number {
  if (!rates.length) return 0;
  return rates.reduce((a, b) => a + b, 0) / rates.length;
}

/**
 * Three dynamic value-optimization bullets for Page 3.
 */
export function buildStrategicRecommendations(
  matrix: ForecastMatrixWithDiagnostics,
  locale: ValuationLocale,
): StrategicRecommendations {
  const { bear, base, bull } = scenarioValues(matrix);
  const currency = matrix.meta.currency || 'ILS';
  const wacc = matrix.assumptions.wacc;
  const growth = avgGrowth(matrix.assumptions.revenue_growth_rates ?? []);
  const margin = ebitdaMargin(matrix);
  const bullFmt = formatMoney(bull, currency, locale);
  const bearFmt = formatMoney(bear, currency, locale);
  const spreadPct = bear > 0 ? ((bull - bear) / bear) * 100 : 0;

  const bulletsHe: string[] = [];
  const bulletsEn: string[] = [];

  bulletsHe.push(
    `כדי לדחוף את ההערכה לכיוון התרחיש השורי של ${bullFmt}, מומלץ להפחית ריכוזיות לקוחות, להגדיל את מנת ההכנסות החוזרות מעל 60%, ולחתום על חוזי שירות ארוכי טווח שמצמצמים את פרמיית הסיכון ב-WACC.`,
  );
  bulletsEn.push(
    `To push valuation toward the Bull Case of ${bullFmt}, reduce customer concentration, grow recurring revenue above 60%, and secure long-term service contracts that compress WACC risk premia.`,
  );

  if (wacc >= 0.14) {
    bulletsHe.push(
      `עלות ההון (${(wacc * 100).toFixed(1)}%) גבוהה — בצעו מיצוב מחדש של מבנה ההון: החלפת חוב יקר בחוב זול יותר, הוכחת יציבות תזרימית ל-12 חודשים, והצגת מדדי unit economics עקביים לפני גיוס או מו"מ.`,
    );
    bulletsEn.push(
      `With elevated WACC (${(wacc * 100).toFixed(1)}%), restructure capital: refinance expensive debt, demonstrate 12-month cash stability, and present consistent unit economics before fundraising or negotiations.`,
    );
  } else if (margin >= 0.18) {
    bulletsHe.push(
      `שולי EBITDA של ${(margin * 100).toFixed(1)}% מצביעים על יעילות תפעולית — מומלץ להשקיע את עודפי התזרים בהרחבת שוק (Geo/Product) תוך שמירה על שוליים, מה שיכול להרחיב את טווח הביטחון מעל ${bullFmt}.`,
    );
    bulletsEn.push(
      `EBITDA margins of ${(margin * 100).toFixed(1)}% signal operational efficiency — reinvest excess cash into geo/product expansion while protecting margins to widen the confidence band above ${bullFmt}.`,
    );
  } else {
    bulletsHe.push(
      `שוליים מתונים מחייבים תוכנית שיפור רווחיות: ייעול COGS, אוטומציה של תהליכי מכירה, ומיקוד בסגמנטים בעלי LTV/CAC גבוה — צעדים שיכולים להעלות את תרחיש הבסיס מ-${formatMoney(base, currency, locale)}.`,
    );
    bulletsEn.push(
      `Moderate margins require a profitability roadmap: COGS optimization, sales automation, and high LTV/CAC segment focus — actions that can lift the Base Case from ${formatMoney(base, currency, locale)}.`,
    );
  }

  if (spreadPct > 30 || growth < 0.06) {
    bulletsHe.push(
      `פער תרחישים של ${spreadPct.toFixed(0)}% (מ-${bearFmt} ועד ${bullFmt}) משקף אי-ודאות — הגדירו אבני דרך רבעוניות מדידות (ARR, Churn, CAC Payback) כדי לצמצם את פרמיית הסיכון ולחזק את ציון הביטחון (${matrix.meta.confidence_score}%).`,
    );
    bulletsEn.push(
      `A ${spreadPct.toFixed(0)}% scenario spread (${bearFmt}–${bullFmt}) reflects uncertainty — set measurable quarterly milestones (ARR, churn, CAC payback) to compress risk premia and strengthen the confidence score (${matrix.meta.confidence_score}%).`,
    );
  } else {
    bulletsHe.push(
      `מומנטום צמיחה של ${(growth * 100).toFixed(1)}% בשנה תומך בנרטיב הערכה חיובי — חזקו את איכות הנתונים הפיננסיים ובצעו בדיקת רגישות ל-WACC ולצמיחה לטווח ארוך לפני הפצת הדוח לגורמים חיצוניים.`,
    );
    bulletsEn.push(
      `Growth momentum of ${(growth * 100).toFixed(1)}% annually supports a positive valuation narrative — strengthen financial data quality and run WACC / terminal-growth sensitivity before external distribution.`,
    );
  }

  return {
    title:
      locale === 'he'
        ? 'תובנות אלגוריתמיות והמלצות להשבחת שווי'
        : 'Algorithmic Insights & Value Optimization',
    bullets: (locale === 'he' ? bulletsHe : bulletsEn).slice(0, 3),
    disclaimer:
      locale === 'he'
        ? 'הצהרת אחריות: דוח זה נוצר באמצעות מודל אלגוריתמי של Equify by SBC ואינו מהווה ייעוץ פיננסי, הערכת שווי מוסמכת או חוות דעת מקצועית. התוצאות מבוססות על הנחות שהוזנו על ידי המשתמש ואינן מהוות המלצה לפעולה. יש להיוועץ ביועץ פיננסי מוסמך לפני קבלת החלטות השקעה, מימון או מכירה.'
        : 'Disclaimer: This report is generated by the Equify by SBC algorithmic model and does not constitute financial advice, certified appraisal, or professional opinion. Results are based on user-supplied assumptions and are not a recommendation to act. Consult a qualified financial advisor before making investment, financing, or sale decisions.',
  };
}
